# Generated by Django 6.0.3 on 2026-08-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile_allowed_topics_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(help_text='Paragraph content of the additional topic (supports markdown)')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='additional_topics/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='additional_topics/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='additional_topics/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
