# Generated by Django 6.0.3 on 2026-09-30 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_whiteboardstroke'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='video_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
